[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "get-snirh"
version = "0.1.2"
description = "A Python package to automate downloading water resource data from SNIRH"
readme = "README.md"
requires-python = ">=3.8"
authors = [
    {name = "Rui Hugman"},
    {name = "Luis Costa"},
]
keywords = ["snirh", "water", "hydrology", "portugal", "environment", "data"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Hydrology",
]
dependencies = [
    "pandas>=2.0.0",
    "requests>=2.25.0",
]

[project.urls]
"Homepage" = "https://github.com/rhugman/get-snirh"
"Repository" = "https://github.com/rhugman/get-snirh"
"Bug Tracker" = "https://github.com/rhugman/get-snirh/issues"

[tool.setuptools.package-data]
"get_snirh" = ["data/*.csv", "data/*.txt", "data/*.json"]
